// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: SR.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
using FreeSR.Proto;

namespace FreeSR.Proto
{

    [global::ProtoBuf.ProtoContract()]
    public partial class ClientDownloadDataScNotify : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(11, Name = @"download_data")]
        public ClientDownloadData DownloadData { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ContentPackageInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(12, Name = @"status")]
        public ContentPackageStatus Status { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"cur_map_entry_id")]
        public uint CurMapEntryId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ContentPackageData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(2, Name = @"cur_content_id")]
        public uint CurContentId { get; set; }

        [global::ProtoBuf.ProtoMember(14, Name = @"content_package_list")]
        public global::System.Collections.Generic.List<ContentPackageInfo> ContentPackageLists { get; } = new global::System.Collections.Generic.List<ContentPackageInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ContentPackageSyncDataScNotify : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(5, Name = @"data")]
        public ContentPackageData Data { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AvatarSync : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(10, Name = @"avatar_list")]
        public global::System.Collections.Generic.List<Avatar> AvatarLists { get; } = new global::System.Collections.Generic.List<Avatar>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PlayerSyncScNotify : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(10, Name = @"avatar_sync")]
        public AvatarSync AvatarSync { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetLineupAvatarDataCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LineupAvatarData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(6, Name = @"avatar_type")]
        public AvatarType AvatarType { get; set; }

        [global::ProtoBuf.ProtoMember(11, Name = @"hp")]
        public uint Hp { get; set; }

        [global::ProtoBuf.ProtoMember(12, Name = @"id")]
        public uint Id { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetLineupAvatarDataScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(11, Name = @"AvatarData")]
        public global::System.Collections.Generic.List<LineupAvatarData> AvatarDatas { get; } = new global::System.Collections.Generic.List<LineupAvatarData>();

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AvatarPathChangedNotify : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(3, Name = @"base_avatar_id")]
        public uint BaseAvatarId { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"path_type")]
        public MultiPathAvatarType PathType { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SetAvatarPathCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(13, Name = @"basic_type")]
        public MultiPathAvatarType BasicType { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SetAvatarPathScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(9, Name = @"retcode")]
        public uint Retcode { get; set; }

        [global::ProtoBuf.ProtoMember(14, Name = @"basic_type")]
        public MultiPathAvatarType BasicType { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SetLineupNameCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(9, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(11, Name = @"index")]
        public uint Index { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SetLineupNameScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(12, Name = @"retcode")]
        public uint Retcode { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(7, Name = @"index")]
        public uint Index { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetSceneMapInfoCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(14, Name = @"cur_map_entry_id")]
        public uint CurMapEntryId { get; set; }

        [global::ProtoBuf.ProtoMember(12, Name = @"PHHDECMGCBC")]
        public uint Phhdecmgcbc { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"MFDIBEECLPP")]
        public bool Mfdibeeclpp { get; set; }

        [global::ProtoBuf.ProtoMember(1, Name = @"entry_id_list", IsPacked = true)]
        public uint[] EntryIdLists { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MazeGroup : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(2, Name = @"OAHPEFAHPPP")]
        public bool Oahpefahppp { get; set; }

        [global::ProtoBuf.ProtoMember(13, Name = @"group_id")]
        public uint GroupId { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"modify_time")]
        public long ModifyTime { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"FFFFOKHJKEP", IsPacked = true)]
        public uint[] Ffffokhjkeps { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MazeProp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(4, Name = @"config_id")]
        public uint ConfigId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"state")]
        public uint State { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"group_id")]
        public uint GroupId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MazeChest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(4, Name = @"map_info_chest_type")]
        public ChestType MapInfoChestType { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"total_amount_list")]
        public uint TotalAmountList { get; set; }

        [global::ProtoBuf.ProtoMember(12, Name = @"unlocked_amount_list")]
        public uint UnlockedAmountList { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SceneMapInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(8, Name = @"dynamic_values")]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<string, int> DynamicValues { get; } = new global::System.Collections.Generic.Dictionary<string, int>();

        [global::ProtoBuf.ProtoMember(11, Name = @"unlocked_teleport_list", IsPacked = true)]
        public uint[] UnlockedTeleportLists { get; set; }

        [global::ProtoBuf.ProtoMember(1, Name = @"maze_group_list")]
        public global::System.Collections.Generic.List<MazeGroup> MazeGroupLists { get; } = new global::System.Collections.Generic.List<MazeGroup>();

        [global::ProtoBuf.ProtoMember(9, Name = @"entry_id")]
        public uint EntryId { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"unlocked_chest_list")]
        public global::System.Collections.Generic.List<MazeChest> UnlockedChestLists { get; } = new global::System.Collections.Generic.List<MazeChest>();

        [global::ProtoBuf.ProtoMember(10, Name = @"lighten_section_list", IsPacked = true)]
        public uint[] LightenSectionLists { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"EOBFHOFKJFM")]
        public uint Eobfhofkjfm { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"PHHDECMGCBC")]
        public uint Phhdecmgcbc { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"retcode")]
        public uint Retcode { get; set; }

        [global::ProtoBuf.ProtoMember(12, Name = @"PHPHBMIAOGG")]
        public uint Phphbmiaogg { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"maze_prop_list")]
        public global::System.Collections.Generic.List<MazeProp> MazePropLists { get; } = new global::System.Collections.Generic.List<MazeProp>();

        [global::ProtoBuf.ProtoMember(13, Name = @"cur_map_entry_id")]
        public uint CurMapEntryId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetSceneMapInfoScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(10, Name = @"MFDIBEECLPP")]
        public bool Mfdibeeclpp { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"map_list")]
        public global::System.Collections.Generic.List<SceneMapInfo> MapLists { get; } = new global::System.Collections.Generic.List<SceneMapInfo>();

        [global::ProtoBuf.ProtoMember(9, Name = @"retcode")]
        public uint Retcode { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetCurSceneInfoCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetMultiPathAvatarInfoCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetCurSceneInfoScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(15, Name = @"retcode")]
        public uint Retcode { get; set; }

        [global::ProtoBuf.ProtoMember(11, Name = @"scene")]
        public SceneInfo Scene { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetBasicInfoCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetAllLineupDataCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetCurLineupDataCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EnterSceneByServerScNotify : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(14, Name = @"lineup")]
        public LineupInfo Lineup { get; set; }

        [global::ProtoBuf.ProtoMember(11, Name = @"reason")]
        public EnterSceneReason Reason { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"scene")]
        public SceneInfo Scene { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SceneEntityMoveScNotify : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(10, Name = @"entity_id")]
        public uint EntityId { get; set; }

        [global::ProtoBuf.ProtoMember(15, Name = @"motion")]
        public MotionInfo Motion { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"entry_id")]
        public uint EntryId { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"client_pos_version")]
        public uint ClientPosVersion { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StartCocoonStageCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(3, Name = @"wave")]
        public uint Wave { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"world_level")]
        public uint WorldLevel { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"prop_entity_id")]
        public uint PropEntityId { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"cocoon_id")]
        public uint CocoonId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StartCocoonStageScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(11)]
        public uint CocoonId { get; set; }

        [global::ProtoBuf.ProtoMember(15)]
        public uint PropEntityId { get; set; }

        [global::ProtoBuf.ProtoMember(12)]
        public uint Wave { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public uint Retcode { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        public SceneBattleInfo BattleInfo { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BattleBuff : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public uint Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"level")]
        public uint Level { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"owner_id")]
        public uint OwnerId { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"wave_flag")]
        public uint WaveFlag { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"target_index_list", IsPacked = true)]
        public uint[] TargetIndexLists { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"dynamic_values")]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<string, float> DynamicValues { get; } = new global::System.Collections.Generic.Dictionary<string, float>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BattleEquipment : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public uint Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"level")]
        public uint Level { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"promotion")]
        public uint Promotion { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"rank")]
        public uint Rank { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BattleRelic : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public uint Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"level")]
        public uint Level { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"main_affix_id")]
        public uint MainAffixId { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"sub_affix_list")]
        public global::System.Collections.Generic.List<RelicAffix> SubAffixLists { get; } = new global::System.Collections.Generic.List<RelicAffix>();

        [global::ProtoBuf.ProtoMember(5, Name = @"unique_id")]
        public uint UniqueId { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"set_id")]
        public uint SetId { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"type")]
        public uint Type { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"FIAKNHKJJBD")]
        public uint Fiaknhkjjbd { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BattleAvatar : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"avatar_type")]
        public AvatarType AvatarType { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"id")]
        public uint Id { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"level")]
        public uint Level { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"rank")]
        public uint Rank { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"index")]
        public uint Index { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"skilltree_list")]
        public global::System.Collections.Generic.List<AvatarSkillTree> SkilltreeLists { get; } = new global::System.Collections.Generic.List<AvatarSkillTree>();

        [global::ProtoBuf.ProtoMember(7, Name = @"equipment_list")]
        public global::System.Collections.Generic.List<BattleEquipment> EquipmentLists { get; } = new global::System.Collections.Generic.List<BattleEquipment>();

        [global::ProtoBuf.ProtoMember(8, Name = @"hp")]
        public uint Hp { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"promotion")]
        public uint Promotion { get; set; }

        [global::ProtoBuf.ProtoMember(11, Name = @"relic_list")]
        public global::System.Collections.Generic.List<BattleRelic> RelicLists { get; } = new global::System.Collections.Generic.List<BattleRelic>();

        [global::ProtoBuf.ProtoMember(12, Name = @"world_level")]
        public uint WorldLevel { get; set; }

        [global::ProtoBuf.ProtoMember(13, Name = @"assist_uid")]
        public uint AssistUid { get; set; }

        [global::ProtoBuf.ProtoMember(16, Name = @"sp_bar")]
        public SpBarInfo SpBar { get; set; }

        [global::ProtoBuf.ProtoMember(17, Name = @"MPFLNIIKEIC")]
        public uint Mpflniikeic { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SceneBattleInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(14, Name = @"monster_wave_list")]
        public global::System.Collections.Generic.List<SceneMonsterWave> MonsterWaveLists { get; } = new global::System.Collections.Generic.List<SceneMonsterWave>();

        [global::ProtoBuf.ProtoMember(2, Name = @"world_level")]
        public uint WorldLevel { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"buff_list")]
        public global::System.Collections.Generic.List<BattleBuff> BuffLists { get; } = new global::System.Collections.Generic.List<BattleBuff>();

        [global::ProtoBuf.ProtoMember(7, Name = @"battle_avatar_list")]
        public global::System.Collections.Generic.List<BattleAvatar> BattleAvatarLists { get; } = new global::System.Collections.Generic.List<BattleAvatar>();

        [global::ProtoBuf.ProtoMember(6, Name = @"logic_random_seed")]
        public uint LogicRandomSeed { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"rounds_limit")]
        public uint RoundsLimit { get; set; }

        [global::ProtoBuf.ProtoMember(1, Name = @"stage_id")]
        public uint StageId { get; set; }

        [global::ProtoBuf.ProtoMember(12, Name = @"battle_id")]
        public uint BattleId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SceneMonsterWaveParam : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(10, Name = @"FOBGFMKKIPK")]
        public uint Fobgfmkkipk { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"NKAAPFHHLCN")]
        public uint Nkaapfhhlcn { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"level")]
        public uint Level { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"DDAFGBCJFMG")]
        public uint Ddafgbcjfmg { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SceneMonsterWave : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(14, Name = @"stage_id")]
        public uint StageId { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"monster_list")]
        public global::System.Collections.Generic.List<SceneMonster> MonsterLists { get; } = new global::System.Collections.Generic.List<SceneMonster>();

        [global::ProtoBuf.ProtoMember(10, Name = @"wave_id")]
        public uint WaveId { get; set; }

        [global::ProtoBuf.ProtoMember(13, Name = @"wave_param")]
        public SceneMonsterWaveParam WaveParam { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SceneEntityMoveCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(10, Name = @"NJPEMCAGPIB")]
        public ulong Njpemcagpib { get; set; }

        [global::ProtoBuf.ProtoMember(15, Name = @"entity_motion_list")]
        public global::System.Collections.Generic.List<EntityMotion> EntityMotionLists { get; } = new global::System.Collections.Generic.List<EntityMotion>();

        [global::ProtoBuf.ProtoMember(3, Name = @"entry_id")]
        public uint EntryId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EntityMotion : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(11, Name = @"map_layer")]
        public uint MapLayer { get; set; }

        [global::ProtoBuf.ProtoMember(1, Name = @"motion")]
        public MotionInfo Motion { get; set; }

        [global::ProtoBuf.ProtoMember(15, Name = @"entity_id")]
        public uint EntityId { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"GCHCPPDDMAD")]
        public bool Gchcppddmad { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SceneMonster : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(15, Name = @"monster_id")]
        public uint MonsterId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SceneEntityInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"motion")]
        public MotionInfo Motion { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"entity_id")]
        public uint EntityId { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"group_id")]
        public uint GroupId { get; set; }

        [global::ProtoBuf.ProtoMember(13, Name = @"inst_id")]
        public uint InstId { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"prop")]
        public ScenePropInfo Prop { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ScenePropInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(11, Name = @"life_time_ms")]
        public uint LifeTimeMs { get; set; }

        [global::ProtoBuf.ProtoMember(12, Name = @"prop_state")]
        public uint PropState { get; set; }

        [global::ProtoBuf.ProtoMember(14, Name = @"trigger_name_list")]
        public global::System.Collections.Generic.List<string> TriggerNameLists { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(10, Name = @"prop_id")]
        public uint PropId { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"create_time_ms")]
        public ulong CreateTimeMs { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SceneEntityGroupInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(8, Name = @"entity_list")]
        public global::System.Collections.Generic.List<SceneEntityInfo> EntityLists { get; } = new global::System.Collections.Generic.List<SceneEntityInfo>();

        [global::ProtoBuf.ProtoMember(4, Name = @"state")]
        public uint State { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"group_id")]
        public uint GroupId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SceneGroupState : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(10, Name = @"group_id")]
        public uint GroupId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"state")]
        public uint State { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"is_default")]
        public bool IsDefault { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RelicAffix : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"affix_id")]
        public uint AffixId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"cnt")]
        public uint Cnt { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"step")]
        public uint Step { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SceneInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(15, Name = @"world_id")]
        public uint WorldId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"plane_id")]
        public uint PlaneId { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"game_mode_type")]
        public uint GameModeType { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"entity_list")]
        public global::System.Collections.Generic.List<SceneEntityInfo> EntityLists { get; } = new global::System.Collections.Generic.List<SceneEntityInfo>();

        [global::ProtoBuf.ProtoMember(13, Name = @"entry_id")]
        public uint EntryId { get; set; }

        [global::ProtoBuf.ProtoMember(14, Name = @"leader_entity_id")]
        public uint LeaderEntityId { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"client_pos_version")]
        public uint ClientPosVersion { get; set; }

        [global::ProtoBuf.ProtoMember(1577, Name = @"group_state_list")]
        public global::System.Collections.Generic.List<SceneGroupState> GroupStateLists { get; } = new global::System.Collections.Generic.List<SceneGroupState>();

        [global::ProtoBuf.ProtoMember(1, Name = @"group_id_list", IsPacked = true)]
        public uint[] GroupIdLists { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"lighten_section_list", IsPacked = true)]
        public uint[] LightenSectionLists { get; set; }

        [global::ProtoBuf.ProtoMember(11, Name = @"floor_id")]
        public uint FloorId { get; set; }

        [global::ProtoBuf.ProtoMember(1458, Name = @"dynamic_values")]
        [global::ProtoBuf.ProtoMap(ValueFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public global::System.Collections.Generic.Dictionary<string, int> DynamicValues { get; } = new global::System.Collections.Generic.Dictionary<string, int>();

        [global::ProtoBuf.ProtoMember(1909, Name = @"entity_group_list")]
        public global::System.Collections.Generic.List<SceneEntityGroupInfo> EntityGroupLists { get; } = new global::System.Collections.Generic.List<SceneEntityGroupInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Vector : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(14, Name = @"x", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int X { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"y", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int Y { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"z", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int Z { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MotionInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(14, Name = @"pos")]
        public Vector Pos { get; set; }

        [global::ProtoBuf.ProtoMember(13, Name = @"rot")]
        public Vector Rot { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SpBarInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"cur_amount")]
        public uint CurAmount { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"max_amount")]
        public uint MaxAmount { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetAvatarDataCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"base_avatar_id_list", IsPacked = true)]
        public uint[] BaseAvatarIdLists { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"is_get_all")]
        public bool IsGetAll { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetAvatarDataScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(14, Name = @"retcode")]
        public uint Retcode { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"unlocked_skin_id_list", IsPacked = true)]
        public uint[] UnlockedSkinIdLists { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"is_all")]
        public bool IsAll { get; set; }

        [global::ProtoBuf.ProtoMember(13, Name = @"avatar_list")]
        public global::System.Collections.Generic.List<Avatar> AvatarLists { get; } = new global::System.Collections.Generic.List<Avatar>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Avatar : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(15, Name = @"base_avatar_id")]
        public uint BaseAvatarId { get; set; }

        [global::ProtoBuf.ProtoMember(1, Name = @"level")]
        public uint Level { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"equipment_unique_id")]
        public uint EquipmentUniqueId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"equip_relic_list")]
        public global::System.Collections.Generic.List<EquipRelic> EquipRelicLists { get; } = new global::System.Collections.Generic.List<EquipRelic>();

        [global::ProtoBuf.ProtoMember(14, Name = @"skilltree_list")]
        public global::System.Collections.Generic.List<AvatarSkillTree> SkilltreeLists { get; } = new global::System.Collections.Generic.List<AvatarSkillTree>();

        [global::ProtoBuf.ProtoMember(4, Name = @"first_met_timestamp")]
        public ulong FirstMetTimestamp { get; set; }

        [global::ProtoBuf.ProtoMember(13, Name = @"rank")]
        public uint Rank { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"JPDFAPCHADH")]
        public uint Jpdfapchadh { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"is_marked")]
        public bool IsMarked { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"exp")]
        public uint Exp { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"promotion")]
        public uint Promotion { get; set; }

        [global::ProtoBuf.ProtoMember(11, Name = @"taken_rewards", IsPacked = true)]
        public uint[] TakenRewards { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetCurLineupDataScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(15, Name = @"lineup")]
        public LineupInfo Lineup { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"retcode")]
        public uint Retcode { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetAllLineupDataScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"cur_index")]
        public uint CurIndex { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"lineup_list")]
        public global::System.Collections.Generic.List<LineupInfo> LineupLists { get; } = new global::System.Collections.Generic.List<LineupInfo>();

        [global::ProtoBuf.ProtoMember(7, Name = @"retcode")]
        public uint Retcode { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ChangeLineupLeaderCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(8, Name = @"slot")]
        public uint Slot { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ChangeLineupLeaderScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(11, Name = @"retcode")]
        public uint Retcode { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"slot")]
        public uint Slot { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class JoinLineupCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(2, Name = @"slot")]
        public uint Slot { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"index")]
        public uint Index { get; set; }

        [global::ProtoBuf.ProtoMember(11, Name = @"base_avatar_id")]
        public uint BaseAvatarId { get; set; }

        [global::ProtoBuf.ProtoMember(13, Name = @"is_virtual")]
        public bool IsVirtual { get; set; }

        [global::ProtoBuf.ProtoMember(15, Name = @"avatar_type")]
        public AvatarType AvatarType { get; set; }

        [global::ProtoBuf.ProtoMember(14, Name = @"plane_id")]
        public uint PlaneId { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"extra_lineup_type")]
        public ExtraLineupType ExtraLineupType { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class JoinLineupScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(5, Name = @"retcode")]
        public uint Retcode { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SwapLineupCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(10, Name = @"is_virtual")]
        public bool IsVirtual { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"INAAMJIBBBF")]
        public uint Inaamjibbbf { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"extra_lineup_type")]
        public ExtraLineupType ExtraLineupType { get; set; }

        [global::ProtoBuf.ProtoMember(13, Name = @"index")]
        public uint Index { get; set; }

        [global::ProtoBuf.ProtoMember(11, Name = @"plane_id")]
        public uint PlaneId { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"FMFMDKOCIEB")]
        public uint Fmfmdkocieb { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ReplaceLineupCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(10, Name = @"is_virtual")]
        public bool IsVirtual { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"FGPALNEPABC")]
        public uint Fgpalnepabc { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"plane_id")]
        public uint PlaneId { get; set; }

        [global::ProtoBuf.ProtoMember(12, Name = @"extra_lineup_type")]
        public ExtraLineupType ExtraLineupType { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"leader_slot")]
        public uint LeaderSlot { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"slots")]
        public global::System.Collections.Generic.List<LineupSlotData> Slots { get; } = new global::System.Collections.Generic.List<LineupSlotData>();

        [global::ProtoBuf.ProtoMember(2, Name = @"index")]
        public uint Index { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ReplaceLineupScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(11, Name = @"retcode")]
        public uint Retcode { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LineupSlotData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(10, Name = @"id")]
        public uint Id { get; set; }

        [global::ProtoBuf.ProtoMember(11, Name = @"avatar_type")]
        public AvatarType AvatarType { get; set; }

        [global::ProtoBuf.ProtoMember(13, Name = @"slot")]
        public uint Slot { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class QuitLineupCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(11, Name = @"extra_lineup_type")]
        public ExtraLineupType ExtraLineupType { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"avatar_type")]
        public AvatarType AvatarType { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"base_avatar_id")]
        public uint BaseAvatarId { get; set; }

        [global::ProtoBuf.ProtoMember(14, Name = @"index")]
        public uint Index { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"is_virtual")]
        public bool IsVirtual { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"plane_id")]
        public uint PlaneId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class QuitLineupScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(13, Name = @"is_virtual")]
        public bool IsVirtual { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"is_mainline")]
        public bool IsMainline { get; set; }

        [global::ProtoBuf.ProtoMember(1, Name = @"base_avatar_id")]
        public uint BaseAvatarId { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"retcode")]
        public uint Retcode { get; set; }

        [global::ProtoBuf.ProtoMember(15, Name = @"plane_id")]
        public uint PlaneId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SyncLineupNotify : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(3, Name = @"reason_list", IsPacked = true)]
        public global::System.Collections.Generic.List<SyncLineupReason> ReasonLists { get; } = new global::System.Collections.Generic.List<SyncLineupReason>();

        [global::ProtoBuf.ProtoMember(14, Name = @"lineup")]
        public LineupInfo Lineup { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetMissionStatusCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(8, Name = @"main_mission_id_list", IsPacked = true)]
        public uint[] MainMissionIdLists { get; set; }

        [global::ProtoBuf.ProtoMember(11, Name = @"mission_event_id_list", IsPacked = true)]
        public uint[] MissionEventIdLists { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"sub_mission_id_list", IsPacked = true)]
        public uint[] SubMissionIdLists { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Mission : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(5, Name = @"id")]
        public uint Id { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"progress")]
        public uint Progress { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"status")]
        public MissionStatus Status { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetMissionStatusScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(9, Name = @"mission_event_status_list")]
        public global::System.Collections.Generic.List<Mission> MissionEventStatusLists { get; } = new global::System.Collections.Generic.List<Mission>();

        [global::ProtoBuf.ProtoMember(6, Name = @"finished_main_mission_id_list", IsPacked = true)]
        public uint[] FinishedMainMissionIdLists { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"sub_mission_status_list")]
        public global::System.Collections.Generic.List<Mission> SubMissionStatusLists { get; } = new global::System.Collections.Generic.List<Mission>();

        [global::ProtoBuf.ProtoMember(1, Name = @"unfinished_main_mission_id_list", IsPacked = true)]
        public uint[] UnfinishedMainMissionIdLists { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"retcode")]
        public uint Retcode { get; set; }

        [global::ProtoBuf.ProtoMember(13, Name = @"disabled_main_mission_id_list", IsPacked = true)]
        public uint[] DisabledMainMissionIdLists { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LineupInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(12, Name = @"KKAPCFFDNCH")]
        public bool Kkapcffdnch { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"avatar_list")]
        public global::System.Collections.Generic.List<LineupAvatar> AvatarLists { get; } = new global::System.Collections.Generic.List<LineupAvatar>();

        [global::ProtoBuf.ProtoMember(11, Name = @"EOIFBNKPBGE", IsPacked = true)]
        public uint[] Eoifbnkpbges { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"FGPALNEPABC")]
        public uint Fgpalnepabc { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"index")]
        public uint Index { get; set; }

        [global::ProtoBuf.ProtoMember(15, Name = @"is_virtual")]
        public bool IsVirtual { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"mp")]
        public uint Mp { get; set; }

        [global::ProtoBuf.ProtoMember(14, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(7, Name = @"extra_lineup_type")]
        public ExtraLineupType ExtraLineupType { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"plane_id")]
        public uint PlaneId { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"LKLPOOEMOHI", IsPacked = true)]
        public uint[] Lklpooemohis { get; set; }

        [global::ProtoBuf.ProtoMember(13, Name = @"leader_slot")]
        public uint LeaderSlot { get; set; }

        [global::ProtoBuf.ProtoMember(1, Name = @"OLBHMCHJGKI", IsPacked = true)]
        public uint[] Olbhmchjgkis { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"max_mp")]
        public uint MaxMp { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LineupAvatar : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(6, Name = @"hp")]
        public uint Hp { get; set; }

        [global::ProtoBuf.ProtoMember(15, Name = @"satiety")]
        public uint Satiety { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"slot")]
        public uint Slot { get; set; }

        [global::ProtoBuf.ProtoMember(1, Name = @"avatar_type")]
        public AvatarType AvatarType { get; set; }

        [global::ProtoBuf.ProtoMember(14, Name = @"sp_bar")]
        public SpBarInfo SpBar { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"id")]
        public uint Id { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PVEBattleResultCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"end_status")]
        public BattleEndStatus EndStatus { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PVEBattleResultScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(3, Name = @"retcode")]
        public uint Retcode { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"end_status")]
        public BattleEndStatus EndStatus { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetTutorialGuideScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(5, Name = @"TutorialGuideList")]
        public global::System.Collections.Generic.List<TutorialGuide> TutorialGuideLists { get; } = new global::System.Collections.Generic.List<TutorialGuide>();

        [global::ProtoBuf.ProtoMember(15)]
        public uint Retcode { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TutorialGuide : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(3)]
        public uint Id { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public TutorialStatus Status { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetTutorialScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(9, Name = @"TutorialList")]
        public global::System.Collections.Generic.List<Tutorial> TutorialLists { get; } = new global::System.Collections.Generic.List<Tutorial>();

        [global::ProtoBuf.ProtoMember(14)]
        public uint Retcode { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Tutorial : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(13)]
        public uint Id { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public TutorialStatus Status { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PlayerLoginCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(8, Name = @"login_random")]
        public ulong LoginRandom { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PlayerLoginScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(13, Name = @"login_random")]
        public ulong LoginRandom { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"basic_info")]
        public PlayerBasicInfo BasicInfo { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"retcode")]
        public uint Retcode { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"stamina")]
        public uint Stamina { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"cur_timezone")]
        public int CurTimezone { get; set; }

        [global::ProtoBuf.ProtoMember(15, Name = @"server_timestamp_ms")]
        public ulong ServerTimestampMs { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PlayerGetTokenCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(3, Name = @"platform_type")]
        public uint PlatformType { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"token")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Token { get; set; } = "";

        [global::ProtoBuf.ProtoMember(7, Name = @"IPOLCNOCFNB")]
        public uint Ipolcnocfnb { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"account_uid")]
        [global::System.ComponentModel.DefaultValue("")]
        public string AccountUid { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5, Name = @"NALKKAPMIGK")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Nalkkapmigk { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"MNFBCAICCED")]
        public uint Mnfbcaicced { get; set; }

        [global::ProtoBuf.ProtoMember(14, Name = @"ICOPIHMOOGH")]
        public uint Icopihmoogh { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"uid")]
        public uint Uid { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PlayerGetTokenScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(10, Name = @"retcode")]
        public uint Retcode { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"uid")]
        public uint Uid { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"secret_key_seed")]
        public ulong SecretKeySeed { get; set; }

        [global::ProtoBuf.ProtoMember(12, Name = @"black_info")]
        public BlackInfo BlackInfo { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"msg")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Msg { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BlackInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"begin_time")]
        public long BeginTime { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"end_time")]
        public long EndTime { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"limit_level")]
        public uint LimitLevel { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"ban_type")]
        public uint BanType { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PlayerBasicInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"nickname")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Nickname { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"level")]
        public uint Level { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"exp")]
        public uint Exp { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"stamina")]
        public uint Stamina { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"mcoin")]
        public uint Mcoin { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"hcoin")]
        public uint Hcoin { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"scoin")]
        public uint Scoin { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"world_level")]
        public uint WorldLevel { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetBasicInfoScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(4)]
        public uint Gender { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"cur_day")]
        public uint CurDay { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"next_recover_time")]
        public long NextRecoverTime { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public bool IsGenderSet { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"gameplay_birthday")]
        public uint GameplayBirthday { get; set; }

        [global::ProtoBuf.ProtoMember(11, Name = @"retcode")]
        public uint Retcode { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"week_cocoon_finished_count")]
        public uint WeekCocoonFinishedCount { get; set; }

        [global::ProtoBuf.ProtoMember(14, Name = @"exchange_times")]
        public uint ExchangeTimes { get; set; }

        [global::ProtoBuf.ProtoMember(13, Name = @"last_set_nickname_time")]
        public long LastSetNicknameTime { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetMultiPathAvatarInfoScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(3, Name = @"retcode")]
        public uint Retcode { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"avatar_type_info_list")]
        public global::System.Collections.Generic.List<MultiPathAvatarTypeInfo> AvatarTypeInfoLists { get; } = new global::System.Collections.Generic.List<MultiPathAvatarTypeInfo>();

        [global::ProtoBuf.ProtoMember(4, Name = @"multi_avatar_type_id_list", IsPacked = true)]
        public uint[] MultiAvatarTypeIdLists { get; set; }

        [global::ProtoBuf.ProtoMember(13, Name = @"current_multi_avatar_id")]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<uint, MultiPathAvatarType> CurrentMultiAvatarIds { get; } = new global::System.Collections.Generic.Dictionary<uint, MultiPathAvatarType>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EquipRelic : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(13, Name = @"relic_unique_id")]
        public uint RelicUniqueId { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"type")]
        public uint Type { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AvatarSkillTree : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"point_id")]
        public uint PointId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"level")]
        public uint Level { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MultiPathAvatarTypeInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(4, Name = @"skill_tree_list")]
        public global::System.Collections.Generic.List<AvatarSkillTree> SkillTreeLists { get; } = new global::System.Collections.Generic.List<AvatarSkillTree>();

        [global::ProtoBuf.ProtoMember(7, Name = @"rank")]
        public uint Rank { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"path_equipment_id")]
        public uint PathEquipmentId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"avatar_id")]
        public MultiPathAvatarType AvatarId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"equip_relic_list")]
        public global::System.Collections.Generic.List<EquipRelic> EquipRelicLists { get; } = new global::System.Collections.Generic.List<EquipRelic>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PlayerHeartbeatCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(11, Name = @"client_time_ms")]
        public ulong ClientTimeMs { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PlayerHeartbeatScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(12, Name = @"server_time_ms")]
        public ulong ServerTimeMs { get; set; }

        [global::ProtoBuf.ProtoMember(11, Name = @"client_time_ms")]
        public ulong ClientTimeMs { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"download_data")]
        public ClientDownloadData DownloadData { get; set; }

        [global::ProtoBuf.ProtoMember(13, Name = @"retcode")]
        public uint Retcode { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ClientDownloadData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"version")]
        public uint Version { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"time")]
        public long Time { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"data")]
        public byte[] Data { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ServerData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"title")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Title { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"dispatch_url")]
        [global::System.ComponentModel.DefaultValue("")]
        public string DispatchUrl { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"env_type")]
        [global::System.ComponentModel.DefaultValue("")]
        public string EnvType { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5, Name = @"display_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string DisplayName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(6, Name = @"msg")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Msg { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GlobalDispatchData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"msg")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Msg { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"OOIJOCPELAE")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Ooijocpelae { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"server_list")]
        public global::System.Collections.Generic.List<ServerData> ServerLists { get; } = new global::System.Collections.Generic.List<ServerData>();

        [global::ProtoBuf.ProtoMember(5, Name = @"top_server_region_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string TopServerRegionName { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Gateserver : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(825, Name = @"b6")]
        public bool B6 { get; set; }

        [global::ProtoBuf.ProtoMember(12, Name = @"retcode")]
        public uint Retcode { get; set; }

        [global::ProtoBuf.ProtoMember(1457, Name = @"b9")]
        public bool B9 { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"lua_url")]
        [global::System.ComponentModel.DefaultValue("")]
        public string LuaUrl { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5, Name = @"region_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string RegionName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(1, Name = @"b1")]
        public bool B1 { get; set; }

        [global::ProtoBuf.ProtoMember(1113, Name = @"ifix_url")]
        [global::System.ComponentModel.DefaultValue("")]
        public string IfixUrl { get; set; } = "";

        [global::ProtoBuf.ProtoMember(1583, Name = @"ifix_version")]
        [global::System.ComponentModel.DefaultValue("")]
        public string IfixVersion { get; set; } = "";

        [global::ProtoBuf.ProtoMember(14, Name = @"ex_resource_url")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ExResourceUrl { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"ip")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Ip { get; set; } = "";

        [global::ProtoBuf.ProtoMember(11, Name = @"msg")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Msg { get; set; } = "";

        [global::ProtoBuf.ProtoMember(1176, Name = @"b8")]
        public bool B8 { get; set; }

        [global::ProtoBuf.ProtoMember(1028, Name = @"b7")]
        public bool B7 { get; set; }

        [global::ProtoBuf.ProtoMember(297, Name = @"b3")]
        public bool B3 { get; set; }

        [global::ProtoBuf.ProtoMember(593, Name = @"b5")]
        public bool B5 { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"b2")]
        public bool B2 { get; set; }

        [global::ProtoBuf.ProtoMember(661, Name = @"lua_version")]
        [global::System.ComponentModel.DefaultValue("")]
        public string LuaVersion { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"port")]
        public uint Port { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"asset_bundle_url")]
        [global::System.ComponentModel.DefaultValue("")]
        public string AssetBundleUrl { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public enum AvatarType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"AVATAR_TYPE_NONE")]
        AvatarTypeNone = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"AVATAR_TRIAL_TYPE")]
        AvatarTrialType = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"AVATAR_LIMIT_TYPE")]
        AvatarLimitType = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"AVATAR_FORMAL_TYPE")]
        AvatarFormalType = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"AVATAR_ASSIST_TYPE")]
        AvatarAssistType = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"AVATAR_AETHER_DIVIDE_TYPE")]
        AvatarAetherDivideType = 5,
        [global::ProtoBuf.ProtoEnum(Name = @"AVATAR_UPGRADE_AVAILABLE_TYPE")]
        AvatarUpgradeAvailableType = 6,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum BattleEndStatus
    {
        [global::ProtoBuf.ProtoEnum(Name = @"BATTLE_END_NONE")]
        BattleEndNone = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"BATTLE_END_WIN")]
        BattleEndWin = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"BATTLE_END_LOSE")]
        BattleEndLose = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"BATTLE_END_QUIT")]
        BattleEndQuit = 3,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum ExtraLineupType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"LINEUP_NONE")]
        LineupNone = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"LINEUP_CHALLENGE")]
        LineupChallenge = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"LINEUP_ROGUE")]
        LineupRogue = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"LINEUP_CHALLENGE_2")]
        LineupChallenge2 = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"LINEUP_CHALLENGE_3")]
        LineupChallenge3 = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"LINEUP_ROGUE_CHALLENGE")]
        LineupRogueChallenge = 5,
        [global::ProtoBuf.ProtoEnum(Name = @"LINEUP_STAGE_TRIAL")]
        LineupStageTrial = 6,
        [global::ProtoBuf.ProtoEnum(Name = @"LINEUP_ROGUE_TRIAL")]
        LineupRogueTrial = 7,
        [global::ProtoBuf.ProtoEnum(Name = @"LINEUP_ACTIVITY")]
        LineupActivity = 8,
        [global::ProtoBuf.ProtoEnum(Name = @"LINEUP_BOXING_CLUB")]
        LineupBoxingClub = 9,
        [global::ProtoBuf.ProtoEnum(Name = @"LINEUP_TREASURE_DUNGEON")]
        LineupTreasureDungeon = 11,
        [global::ProtoBuf.ProtoEnum(Name = @"LINEUP_CHESS_ROGUE")]
        LineupChessRogue = 12,
        [global::ProtoBuf.ProtoEnum(Name = @"LINEUP_HELIOBUS")]
        LineupHeliobus = 13,
        [global::ProtoBuf.ProtoEnum(Name = @"LINEUP_TOURN_ROGUE")]
        LineupTournRogue = 14,
        [global::ProtoBuf.ProtoEnum(Name = @"LINEUP_RELIC_ROGUE")]
        LineupRelicRogue = 15,
        [global::ProtoBuf.ProtoEnum(Name = @"LINEUP_ARCADE_ROGUE")]
        LineupArcadeRogue = 16,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum MultiPathAvatarType
    {
        MultiPathAvatarTypeNone = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"Mar_7thKnightType")]
        Mar7thKnightType = 1001,
        [global::ProtoBuf.ProtoEnum(Name = @"Mar_7thRogueType")]
        Mar7thRogueType = 1224,
        BoyWarriorType = 8001,
        GirlWarriorType = 8002,
        BoyKnightType = 8003,
        GirlKnightType = 8004,
        BoyShamanType = 8005,
        GirlShamanType = 8006,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum ChestType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"MAP_INFO_CHEST_TYPE_NONE")]
        MapInfoChestTypeNone = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"MAP_INFO_CHEST_TYPE_NORMAL")]
        MapInfoChestTypeNormal = 101,
        [global::ProtoBuf.ProtoEnum(Name = @"MAP_INFO_CHEST_TYPE_CHALLENGE")]
        MapInfoChestTypeChallenge = 102,
        [global::ProtoBuf.ProtoEnum(Name = @"MAP_INFO_CHEST_TYPE_PUZZLE")]
        MapInfoChestTypePuzzle = 104,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum Gender
    {
        GenderNone = 0,
        GenderMan = 1,
        GenderWoman = 2,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum LanguageType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"LANGUAGE_NONE")]
        LanguageNone = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"LANGUAGE_SC")]
        LanguageSc = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"LANGUAGE_TC")]
        LanguageTc = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"LANGUAGE_EN")]
        LanguageEn = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"LANGUAGE_KR")]
        LanguageKr = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"LANGUAGE_JP")]
        LanguageJp = 5,
        [global::ProtoBuf.ProtoEnum(Name = @"LANGUAGE_FR")]
        LanguageFr = 6,
        [global::ProtoBuf.ProtoEnum(Name = @"LANGUAGE_DE")]
        LanguageDe = 7,
        [global::ProtoBuf.ProtoEnum(Name = @"LANGUAGE_ES")]
        LanguageEs = 8,
        [global::ProtoBuf.ProtoEnum(Name = @"LANGUAGE_PT")]
        LanguagePt = 9,
        [global::ProtoBuf.ProtoEnum(Name = @"LANGUAGE_RU")]
        LanguageRu = 10,
        [global::ProtoBuf.ProtoEnum(Name = @"LANGUAGE_TH")]
        LanguageTh = 11,
        [global::ProtoBuf.ProtoEnum(Name = @"LANGUAGE_VI")]
        LanguageVi = 12,
        [global::ProtoBuf.ProtoEnum(Name = @"LANGUAGE_ID")]
        LanguageId = 13,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum PlatformType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"EDITOR")]
        Editor = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"IOS")]
        Ios = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"ANDROID")]
        Android = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"PC")]
        Pc = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"WEB")]
        Web = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"WAP")]
        Wap = 5,
        [global::ProtoBuf.ProtoEnum(Name = @"PS4")]
        Ps4 = 6,
        [global::ProtoBuf.ProtoEnum(Name = @"NINTENDO")]
        Nintendo = 7,
        [global::ProtoBuf.ProtoEnum(Name = @"CLOUD_ANDROID")]
        CloudAndroid = 8,
        [global::ProtoBuf.ProtoEnum(Name = @"CLOUD_PC")]
        CloudPc = 9,
        [global::ProtoBuf.ProtoEnum(Name = @"CLOUD_IOS")]
        CloudIos = 10,
        [global::ProtoBuf.ProtoEnum(Name = @"PS5")]
        Ps5 = 11,
        [global::ProtoBuf.ProtoEnum(Name = @"MAC")]
        Mac = 12,
        [global::ProtoBuf.ProtoEnum(Name = @"CLOUD_MAC")]
        CloudMac = 13,
        [global::ProtoBuf.ProtoEnum(Name = @"CLOUD_WEB_ANDROID")]
        CloudWebAndroid = 20,
        [global::ProtoBuf.ProtoEnum(Name = @"CLOUD_WEB_IOS")]
        CloudWebIos = 21,
        [global::ProtoBuf.ProtoEnum(Name = @"CLOUD_WEB_PC")]
        CloudWebPc = 22,
        [global::ProtoBuf.ProtoEnum(Name = @"CLOUD_WEB_MAC")]
        CloudWebMac = 23,
        [global::ProtoBuf.ProtoEnum(Name = @"CLOUD_WEB_TOUCH")]
        CloudWebTouch = 24,
        [global::ProtoBuf.ProtoEnum(Name = @"CLOUD_WEB_KEYBOARD")]
        CloudWebKeyboard = 25,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum MissionStatus
    {
        [global::ProtoBuf.ProtoEnum(Name = @"MISSION_NONE")]
        MissionNone = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"MISSION_DOING")]
        MissionDoing = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"MISSION_FINISH")]
        MissionFinish = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"MISSION_PREPARED")]
        MissionPrepared = 3,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum BattleEndReason
    {
        [global::ProtoBuf.ProtoEnum(Name = @"BATTLE_END_REASON_NONE")]
        BattleEndReasonNone = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"BATTLE_END_REASON_ALL_DIE")]
        BattleEndReasonAllDie = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"BATTLE_END_REASON_TURN_LIMIT")]
        BattleEndReasonTurnLimit = 2,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum BattleStaticticEventType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"BATTLE_STATICTIC_EVENT_NONE")]
        BattleStaticticEventNone = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"BATTLE_STATICTIC_EVENT_TREASURE_DUNGEON_ADD_EXPLORE")]
        BattleStaticticEventTreasureDungeonAddExplore = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"BATTLE_STATICTIC_EVENT_TREASURE_DUNGEON_OPEN_GRID")]
        BattleStaticticEventTreasureDungeonOpenGrid = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"BATTLE_STATICTIC_EVENT_TREASURE_DUNGEON_PICKUP_ITEM")]
        BattleStaticticEventTreasureDungeonPickupItem = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"BATTLE_STATICTIC_EVENT_TREASURE_DUNGEON_USE_BUFF")]
        BattleStaticticEventTreasureDungeonUseBuff = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"BATTLE_STATICTIC_EVENT_TELEVISION_ACTIVITY_UPDATE_MAZE_BUFF_LAYER")]
        BattleStaticticEventTelevisionActivityUpdateMazeBuffLayer = 5,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum AetherdivideSpiritLineupType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"AETHERDIVIDE_SPIRIT_LINEUP_NONE")]
        AetherdivideSpiritLineupNone = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"AETHERDIVIDE_SPIRIT_LINEUP_NORMAL")]
        AetherdivideSpiritLineupNormal = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"AETHERDIVIDE_SPIRIT_LINEUP_TRIAL")]
        AetherdivideSpiritLineupTrial = 2,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum EnterSceneReason
    {
        [global::ProtoBuf.ProtoEnum(Name = @"ENTER_SCENE_REASON_NONE")]
        EnterSceneReasonNone = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"ENTER_SCENE_REASON_CHALLENGE_TIMEOUT")]
        EnterSceneReasonChallengeTimeout = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"ENTER_SCENE_REASON_ROGUE_TIMEOUT")]
        EnterSceneReasonRogueTimeout = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"ENTER_SCENE_REASON_CHANGE_STORYLINE")]
        EnterSceneReasonChangeStoryline = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"ENTER_SCENE_REASON_DIMENSION_MERGE")]
        EnterSceneReasonDimensionMerge = 4,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum ContentPackageStatus
    {
        [global::ProtoBuf.ProtoEnum(Name = @"ContentPackageStatus_None")]
        ContentPackageStatusNone = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"ContentPackageStatus_Init")]
        ContentPackageStatusInit = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"ContentPackageStatus_Doing")]
        ContentPackageStatusDoing = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"ContentPackageStatus_Finished")]
        ContentPackageStatusFinished = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"ContentPackageStatus_Release")]
        ContentPackageStatusRelease = 4,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum TutorialStatus
    {
        [global::ProtoBuf.ProtoEnum(Name = @"TUTORIAL_NONE")]
        TutorialNone = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"TUTORIAL_UNLOCK")]
        TutorialUnlock = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"TUTORIAL_FINISH")]
        TutorialFinish = 2,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum SyncLineupReason
    {
        [global::ProtoBuf.ProtoEnum(Name = @"SYNC_REASON_NONE")]
        SyncReasonNone = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"SYNC_REASON_MP_ADD")]
        SyncReasonMpAdd = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"SYNC_REASON_MP_ADD_PROP_HIT")]
        SyncReasonMpAddPropHit = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"SYNC_REASON_HP_ADD")]
        SyncReasonHpAdd = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"SYNC_REASON_HP_ADD_PROP_HIT")]
        SyncReasonHpAddPropHit = 4,
    }

}

[global::ProtoBuf.ProtoContract()]
public partial class PlayerHeartBeatCsReq : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(11, Name = @"client_time_ms")]
    public ulong ClientTimeMs { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class PlayerHeartBeatScRsp : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(12, Name = @"server_time_ms")]
    public ulong ServerTimeMs { get; set; }

    [global::ProtoBuf.ProtoMember(11, Name = @"client_time_ms")]
    public ulong ClientTimeMs { get; set; }

    [global::ProtoBuf.ProtoMember(13, Name = @"retcode")]
    public uint Retcode { get; set; }

    [global::ProtoBuf.ProtoMember(10, Name = @"download_data")]
    public ClientDownloadData DownloadData { get; set; }

}
#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
